stages:
  - analyze

sonar-scanner:
  tags:
    - merapi
  only:
    - develop
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  cache:
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.projectKey={{project_key}}
      -Dsonar.sources=src
      -Dsonar.host.url=https://sonar.javan.co.id
      -Dsonar.login=cd0d286a9087c987496379df10fed7ec519dae2e
  when: manual
